name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # 步骤 1: 检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4
      # 步骤 2: 登录到 GitHub Container Registry (GHCR)
      # GITHUB_TOKEN 是由 GitHub Actions 自动提供的，无需手动创建 secret
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # github.actor 是触发工作流的用户名
          password: ${{ secrets.GITHUB_TOKEN }}
      # 步骤 3: 提取 Docker 元数据
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # 对于 GHCR，镜像名称通常是 ghcr.io/OWNER/IMAGE_NAME
          images: ghcr.io/${{ github.repository }} # github.repository 的格式是 owner/repo-name
      # 步骤 4: 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 步骤 5: 构建并推送到 GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max